# Generated by Django 6.0.7 on 2026-07-29 00:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medicos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('area', models.CharField(choices=[('consulta', 'Consulta Presencial'), ('imagenes', 'Imágenes'), ('procedimientos', 'Procedimientos'), ('otro', 'Otro')], default='consulta', max_length=20)),
                ('ubicacion', models.CharField(blank=True, max_length=150)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Box',
                'verbose_name_plural': 'Boxes',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='AsignacionBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.PositiveSmallIntegerField(blank=True, help_text='0=Lunes ... 6=Domingo. Vacío = aplica todos los días.', null=True)),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_box', to='medicos.medico')),
                ('box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='boxes.box')),
            ],
            options={
                'verbose_name': 'Asignación de Box',
                'verbose_name_plural': 'Asignaciones de Box',
                'unique_together': {('medico', 'box', 'dia_semana')},
            },
        ),
    ]
