# Generated by Django 6.0.7 on 2026-07-29 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boxes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='box',
            name='piso',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Piso 1'), (2, 'Piso 2')], default=2),
        ),
    ]
