# Generated by Django 6.0.7 on 2026-08-05 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medico',
            name='duracion_consulta_min',
            field=models.PositiveSmallIntegerField(default=15, help_text='Usada para estimar cuántas citas caben en su oferta horaria de un día.', verbose_name='Duración de consulta (min)'),
        ),
    ]
