# Generated by Django 6.0.7 on 2026-09-21 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicos', '0002_medico_duracion_consulta_min'),
    ]

    operations = [
        migrations.AddField(
            model_name='medico',
            name='id_recurso_oferta',
            field=models.PositiveIntegerField(blank=True, db_index=True, help_text='IDRecurso del archivo ExportarOferta/ExportarBloqueos. Se completa solo la primera vez que el nombre calza, y desde ahí se usa como clave estable aunque el nombre del archivo cambie (ej. le agreguen un segundo nombre).', null=True, unique=True, verbose_name='ID de recurso (Oferta/Bloqueos)'),
        ),
    ]
