# Generated by Django 6.0.7 on 2026-07-29 00:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('boxes', '0001_initial'),
        ('medicos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportacionAgenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo_nombre', models.CharField(max_length=255)),
                ('fecha_importacion', models.DateTimeField(auto_now_add=True)),
                ('filas_procesadas', models.PositiveIntegerField(default=0)),
                ('filas_omitidas', models.PositiveIntegerField(default=0)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Importación de Agenda',
                'verbose_name_plural': 'Importaciones de Agenda',
                'ordering': ['-fecha_importacion'],
            },
        ),
        migrations.CreateModel(
            name='BloqueAgenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especialidad', models.CharField(blank=True, max_length=150)),
                ('id_externo', models.CharField(blank=True, help_text='AppointmentId del sistema origen, solo para evitar duplicar al reimportar. No es dato de paciente.', max_length=64, null=True, unique=True, verbose_name='ID externo')),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('estado', models.CharField(choices=[('citado', 'Citado'), ('confirmado', 'Confirmado'), ('anulado', 'Anulado'), ('bloqueado', 'Bloqueado'), ('atendido', 'Atendido'), ('otro', 'Otro')], default='citado', max_length=20)),
                ('origen', models.CharField(choices=[('importado', 'Importado'), ('manual', 'Manual')], default='manual', max_length=20)),
                ('box', models.ForeignKey(blank=True, help_text='Se propone automáticamente según la asignación fija del médico; puede reasignarse manualmente.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bloques_agenda', to='boxes.box')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloques_agenda', to='medicos.medico')),
                ('importacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bloques', to='agenda.importacionagenda')),
            ],
            options={
                'verbose_name': 'Bloque de Agenda',
                'verbose_name_plural': 'Bloques de Agenda',
                'ordering': ['fecha', 'hora_inicio'],
                'indexes': [models.Index(fields=['fecha', 'medico'], name='agenda_bloq_fecha_6523e0_idx'), models.Index(fields=['fecha', 'box'], name='agenda_bloq_fecha_083d66_idx')],
            },
        ),
    ]
