# Generated by Django 6.0.7 on 2026-08-10 23:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reunion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(unique=True, verbose_name='Fecha de la reunión')),
                ('titulo', models.CharField(blank=True, max_length=200, verbose_name='Título')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Reunión',
                'verbose_name_plural': 'Reuniones',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Diapositiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveSmallIntegerField()),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('plantilla', models.CharField(max_length=200, verbose_name='Plantilla')),
                ('contexto', models.JSONField(default=dict, verbose_name='Datos')),
                ('reunion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diapositivas', to='presentacion.reunion')),
            ],
            options={
                'verbose_name': 'Diapositiva',
                'verbose_name_plural': 'Diapositivas',
                'ordering': ['orden'],
                'unique_together': {('reunion', 'orden')},
            },
        ),
    ]
