# Generated by Django 6.0.7 on 2026-07-29 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medicos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloqueoMedico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.PositiveSmallIntegerField(help_text='0=Lunes ... 6=Domingo.')),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('tipo', models.CharField(choices=[('Partial', 'Parcial'), ('WholeDay', 'Día completo')], default='Partial', max_length=20)),
                ('motivo', models.CharField(blank=True, max_length=200)),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloqueos', to='medicos.medico')),
            ],
            options={
                'verbose_name': 'Bloqueo de médico',
                'verbose_name_plural': 'Bloqueos de médico',
                'ordering': ['dia_semana', 'hora_inicio'],
            },
        ),
        migrations.CreateModel(
            name='OfertaMedico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.PositiveSmallIntegerField(help_text='0=Lunes ... 6=Domingo.')),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ofertas', to='medicos.medico')),
            ],
            options={
                'verbose_name': 'Oferta de médico',
                'verbose_name_plural': 'Ofertas de médico',
                'ordering': ['dia_semana', 'hora_inicio'],
            },
        ),
    ]
