# Generated by Django 6.0.7 on 2026-10-05 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disponibilidad', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloqueomedico',
            name='tipo',
            field=models.CharField(choices=[('Partial', 'Parcial'), ('WholeDay', 'Día completo'), ('Range', 'Rango de fecha/hora')], default='Partial', max_length=20),
        ),
    ]
